language: node_js
node_js:
  - node

cache:
  directories:
    - node_modules

before_script:
  - npm install canvas-sketch-cli -g
  - yarn

script:
  - yarn run website:build
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
